variable "access_key" {}
variable "secret_key" {}
variable "region" {}
variable "availability_zone1" {}
variable "availability_zone2" {}
variable "vpc_cidr" {}
variable "public_subnet_cidr1" {}
variable "public_subnet_cidr2" {}
variable "private_subnet_cidr1" {}
variable "private_subnet_cidr2" {}
variable "hamgmt_subnet_cidr1" {}
variable "hamgmt_subnet_cidr2" {}
variable "attachment_subnet_cidr1" {}
variable "attachment_subnet_cidr2" {}
variable "fgt_bgp_asn" {}
variable "fgt1_private_ip" {}
variable "fgt2_private_ip" {}
variable "tag_name_prefix" {}
variable "tag_name_unique" {}
variable "cwan_creation" {}
variable "cwan_id" {}
variable "cwan_connect_cidr" {}
variable "cwan_bgp_asn" {}
variable "cwan_segment_key" {}
variable "cwan_segment_value" {}
variable "cwan_policy_state" {}